import { Inter } from "next/font/google";
import { authOptions } from '@/pages/api/auth/[...nextauth]';
import { getServerSession } from 'next-auth';
import "./globals.css";
import Link from 'next/link'
import LoginBtn from './LoginBtn';
import LogoutBtn from './LogoutBtn';



const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  let session = await getServerSession(authOptions) //서버컴포넌트에서만 사용가능, 로그인한 회원의 정보를 보여줌
  console.log(session)

  return (
    <html lang="en">
      <body className={inter.className}>
        <div className='navbar'>
          <Link href="/" className='logo'>HYUP's Page</Link>
          <Link href="/">Home</Link>
          <Link href="/list">List</Link>
          <span className='Login-box'>
            {
              session ?
              <span style={{color : 'black'}}>{session.user.name}<LogoutBtn/></span> : <LoginBtn/>
            }
          </span>
        </div>
        {children}
      </body>
    </html>
  );
}
